[server]
enableStaticServing = true

[theme] # You have to add this line

primaryColor = '#FF8C02' # Bright Orange

backgroundColor = '#00325B' # Dark Blue

secondaryBackgroundColor = '#55B2FF' # Lighter Blue


# Color used for almost all text.
textColor = "#fff"

